### ISSUE TITLE
新的 WordPress 5.0 會插入 block-library 造成圖片變成正方形

### ISSUE THREAD

**Issue by YamiOdymel** [teacat/tunalog#5]
![sshot-849](https://user-images.githubusercontent.com/7308718/102210811-a2008580-3f0d-11eb-9269-7239df344902.png)

在主題編輯器安插下列 CSS 即可修正，但尚未測試是否允許不同的圖片尺寸大小。

```css
.wp-block-image img {
    height: auto !important;
}
```

![image](https://user-images.githubusercontent.com/7308718/102210630-62d23480-3f0d-11eb-8717-0ddfc0efc48b.png)
